services:
  runner:
    build: ./runner
    ports:
      - "8080:8080"
      - "6080-6089:6080-6089"
    volumes:
      - ./tests:/tests
    environment:
      - TESTS_DIR=/tests
      - USE_NOVNC=true

  portal:
    build:
      context: ./portal
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8080
        NEXT_PUBLIC_NOVNC_HOST: http://localhost
    ports:
      - "3000:3000"

